#!/bin/bash

echo $@


# maven check 
if [ -z `type -P mvn` ];
then
  echo " mvn not installed.Please install maven ."
  exit
else
  echo mvn check ok
fi


printf "groupId[swf-quickstart]: "
read groupId
echo "groupID = $groupId" 

if [ -z $groupId ];
then
  groupId=swf-quickstart
fi

printf "groupId = $groupId""\n"


printf "artifactId[demo]: "
read artifactId
if [ -z $artifactId ]; 
then
  artifactId=demo
  printf "artifactId = $artifactId\n"
fi


printf "version[1.0.0-SNAPSHOT]: "
read version

if [ -z $version ];
then
  version="1.0.0-SNAPSHOT" 
fi
mvn archetype:create -DgroupId=$groupId -DartifactId=$artifactId
pushd $artifactId
  rm -rf pom.xml
  curl -L  https://raw.github.com/tottokug/swf-quickstart/master/pom.xml | perl -pe "s/\#\#GROUP_ID\#\#/$groupId/g" |perl -pe "s/##ARTIFACT_ID##/$artifactId/g" |perl -pe "s/##VERSION##/$version/g" > pom.xml
popd
exit
