#!/bin/bash

# maven check 
if [ -z `type -P mvn` ];
then
  echo " mvn not installed.Please install maven ."
  exit
fi

groupId=""
while [ -z $groupId ];
do
  echo -n "groupId: "
  read groupId
  echo "groupId = $groupId"
done

artifactId=""
while [ -z $artifactId ];
do
  echo -n "artifactId: "
  read artifactId
  echo "artifactId = $artifactId"
done

version=""
echo -n "version[1.0.0-SNAPSHOT]: "
read version
if [ -z $version ];
then
  version="1.0.0-SNAPSHOT" 
fi

mvn archetype:create -DgroupId=$groupId -DartifactId=$artifactId
exit
pushd $artifactId
  rm -rf pom.xml
  curl -L -O https://raw.github.com/tottokug/swf-quickstart/master/pom.xml
  sed -i "s/##GROUP_ID##/$groupId/g"  pom.xml
  sed -i "s/##ARTIFACT_ID##/$artifactId/g" pom.xml
  sed -i "s/##VERSION##/$version/g" pom.xml
popd
