#!/bin/bash

# maven check 
if [ -z `type -P mvn` ];
then
  echo " mvn not installed.Please install maven ."
  exit
else
  echo mvn check ok
fi

groupId=
while [ -z $groupId ];
do
  printf "groupId: "
  read groupId
  printf "groupId = $groupId""\n"
done

artifactId=
while [ -z $artifactId ];
do
  printf "artifactId: "
  read artifactId
  printf "artifactId = $artifactId\n"
done
version=
printf "version[1.0.0-SNAPSHOT]: "
read version


if [ -z $version ];
then
  version="1.0.0-SNAPSHOT" 
fi
mvn archetype:create -DgroupId=$groupId -DartifactId=$artifactId
exit
pushd $artifactId
exit
  rm -rf pom.xml
exit
  curl -L  https://raw.github.com/tottokug/swf-quickstart/master/pom.xml | perl -pe "s/\#\#GROUP_ID\#\#/$groupId/g" |perl -pe "s/##ARTIFACT_ID##/$artifactId/g" |perl -pe "s/##VERSION##/$version/g" > pom.xml
exit
popd
exit
